const routes = {
    home: '/',
    login: '/login',
    locker: '/mylocker',
    payment: '/mypayments',
    surveys: '/surveys',
    survey: '/surveys/:surveyId',
    invoice: '/invoices',
    feedback: '/feedbacks',
    personal: '/personal',
    chat: '/chat',
    services: '/services',
    newUser: '/newUser',
    visitOperator: '/visitOperator',
    dashboard: '/dashboard',
    contracts: '/contracts',

    admin: '/admin',
    adminLocker: `/admin/locker`,
    adminDashboard: `/admin/dashboard`,
    adminPayments: `/admin/payments`,
    adminInvoices: `/admin/invoices`,
    adminFeedbacks: `/admin/feedbacks`,
    adminPersonal: `/admin/personal`,
    adminRooms: `/admin/rooms`,
    adminUsers: `/admin/residents`,
    adminParkingRights: `/admin/parkingRights`,
    adminEntryRights: `/admin/entryRights`,
    adminLicense: '/admin/residentLicenses',
    adminVisitor: '/admin/visitors',
    adminContract: '/admin/contracts',
    adminChat: '/admin/resident/chat',
}

export default routes