version: '3.8'
services:
  # Room Service PostgreSQL
  room-service-postgres:
    image: postgres:12-alpine
    container_name: room_service_container
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: room_service
    volumes:
      - room_service_postgres_data:/var/lib/postgresql/data
    networks:
      - apartment_network

  # Locker Service PostgreSQL
  locker-service-postgres:
    image: postgres:12-alpine
    container_name: locker_service_container
    ports:
      - "5435:5432"  # Chú ý thay đổi cổng để không bị trùng với service trước
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: locker_service
    volumes:
      - locker_service_postgres_data:/var/lib/postgresql/data
    networks:
      - apartment_network

  # Auth Service PostgreSQL
  auth-service-postgres:
    image: postgres:12-alpine
    container_name: auth_service_container
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: user_service
    volumes:
      - auth_service_postgres_data:/var/lib/postgresql/data
    networks:
      - apartment_network

volumes:
  room_service_postgres_data:
  locker_service_postgres_data:
  auth_service_postgres_data:

networks:
  apartment_network:
    driver: bridge