springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/ #where our registry server is located
  instance:
    prefer-ip-address: true #when the application registers with eureka,
                            #true means: it uses its ip address rather than its hostname

management:
  endpoints:
    web:
      exposure:
        include: "*" #public all API

  endpoint:
    health:
      show-components: always