server:
  port: 9002

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5434/room_service
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.transaction.JTATransactionFactory
      hibernate:
        format_sql: true