spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5434/room_service
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.transaction.JTATransactionFactory
      hibernate:
        format_sql: true

server:
  port: 9002

cloudinary:
  cloud-name: dpc4ckhqs
  api-key: 378389729151436
  api-secret: mWM7_sWVv85g_SDCWV6yZmTfz8g