server:
  port: 9015

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/visitor_service
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.transaction.JTATransactionFactory
      hibernate:
        format_sql: true