spring:
  application:
    name: gateway-service

  config:
    import: configserver:http://localhost:9998 #entrypoint for spring to know where look for the configuration file

  cloud:
    gateway:
      routes:
        - id: room-route
          uri: lb://room-service
          predicates:
            - Path=/room/**
          filters:
            - StripPrefix=1

        - id: auth-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*" #public all API

  endpoint:
    health:
      show-components: always

publicApi:
  GET: > 
    /api/public/**, 
    /swagger-ui/**, 
    /v3/api-docs/**, 
    /api/rooms/list
  POST: >
    /api/auth/login, 
    /api/auth/forgotPassword, 
    /api/auth/resetPassword,
    /api/users/
    
