spring:
  application:
    name: gateway-service

  config:
    import: configserver:http://localhost:9998

  cloud:
    gateway:
      routes:
        - id: room-route
          uri: lb://room-service
          predicates:
            - Path=/room/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: gateway, routes
