spring:
  application:
    name: document-service

  config:
    import: configserver:http://localhost:9998 #entrypoint for spring to know where look for the configuration file

  cloud:
    config:
      fail-fast: true